### ISSUE TITLE
tzTime crashes on loading timezone in Meteor

### ISSUE THREAD

**Issue by craigdrayton** [lmaccherone/tzTime#3]
I've been unable to get Lumenize and tzTime working on my Meteor 1.3 project running in WebStorm IDE.

In following the Lumenize documentation for TimeSeries calculator, I found using .getISOStringInTZ() to crash Meteor if given a timezone string. I believe tzTime is failing to load the timezone files. When I execute the following code on the server it works as expected:

```
var tzTime = require('tzTime');
  console.log(new tzTime.Time('2010-01-02'));
// Works fine, returns time object

  console.log(new tzTime.Time('2011-01-02').getISOStringInTZ('GMT'));
// Works fine, returns 2011-01-02T00:00:00.000Z

  console.log(new tzTime.Time('2011-01-02').getISOStringInTZ('INVALID STRING'));
// As expected, get 'Error: Timezone "INVALID STRING" is either incorrect, or not loaded in the timezone registry at invalidTZError ... /node_modules/tztime/lib/timezone-js.js:43:11
```

But when I execute the following on the server, it crashes Meteor:

```
  console.log(new tzTime.Time('2011-01-02').getISOStringInTZ('Australia/Melbourne'));

TypeError: Cannot read property '5' of undefined
at convertRuleToExactDateAndTime (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/lib/timezone-js.js:246:38)
 at compareDates (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/lib/timezone-js.js:327:13)
at Array.sort (native)
at Array.sort (/Users/craigdrayton/.meteor/packages/es5-shim/.4.5.13.c4kkxr++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:950:16)
at getRule (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/lib/timezone-js.js:348:21)
at [object Object].getTzInfo (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/lib/timezone-js.js:593:16)
at Time.getJSDate (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/src/Time.js:693:36)
at Time.getISOStringInTZ (/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/src/Time.js:711:21)
at server/main.js:14:45
at /Users/craigdrayton/WebstormProjects/dataSandpit/.meteor/local/build/programs/server/boot.js:304:5

```

I can't work out what's going on and would love some help! Thanks.

**Comment by craigdrayton** [comment]
Also, running the following code in the same server file successfully returns the LZW content:

```
var a = fs.readFileSync('/Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/files/tz/africa.lzw', 'utf8');
  console.log(a);
```

**Comment by lmaccherone** [comment]
Try going back to 0.9.4 and 1.0.0 and see if you get the same results. I'm trying to rule out the readFileSync() change that I made in 1.0.1. My instinct is that the first problem is not related to that but the second one is. Alternatively, the second one could be related to the changes made in 0.9.0 so also try 0.7.2. 

I used to use Meteor with tzTime so I'm pretty sure it worked at one point. That's why I'm trying figure out where it stops working. Then again, Meteor has changed also, so it could be unrelated to either of these, but if that's the case than 0.7.2 will also fail and we'll know where to start looking.

Can I ask you what project you use this for? I know there are a couple dozen regular users of Lumenize, but I actually have contact with only 2 of them so I'm always curious.

**Comment by craigdrayton** [comment]
Thanks for such a speedy response.

Running Lumenize 1.0.0 and tzTime 0.9.4 I get the same crash, but a new warning from NPM:

```
Unable to resolve some modules:
  "files" in /Users/craigdrayton/WebstormProjects/dataSandpit/node_modules/tztime/lib/timezone-js.js (os.osx.x86_64)

If you notice problems related to these missing modules, consider running:
  meteor npm install --save files
```

Running the npm command installs a whole lot of stuff but doesn't resolve the problem.

Same applies with Lumenize 0.8.5 and tzTime 0.7.2. I assume it's failing in myLoadZoneFile() at line 92 & 93 of timezone-js.js:

```
  92  // If running in the browser assume tz files are "fileified" into the source and can be "require"d
  93  var files = require('files');
```

Back in Lumenize latest, the following code in the timezone-js.js init function looks to work, decoding the lzw files successfully:

```
      this.loadedZones['australasia'] = true;
      ret = utils.lzwDecode(fs.readFileSync(__dirname + '/../files/tz/australasia.lzw', 'utf8'));
      console.log(ret);
```

As for my project - I am working on a predictive analytics app and want to use Lumenize to help analyse, produce insights on and visualise temporal data. Thanks again.

**Comment by craigdrayton** [comment]
Hi Larry,

I'm still trying to work out this bug. It's failing for me on line 950 of es5-shim.js when arraySort( compareFn) is called:

![screen shot 2016-08-16 at 7 43 00 am](https://cloud.githubusercontent.com/assets/1066478/17680785/5cf548a8-6385-11e6-98d5-229eb026f22a.png)

It's called on line 348 of timezone-js.js at applicableRules.sort(compareDates):

![screen shot 2016-08-16 at 7 53 48 am](https://cloud.githubusercontent.com/assets/1066478/17681062/c3a75482-6386-11e6-91ad-ff635b6c6ffc.png)

If you have some time to take a look, I'd greatly appreciate it.

Cheers,
Craig

**Comment by lmaccherone** [comment]
OK. This looks like it should allow me to figure it out. However, I'm on site at a client all this week and this is going to take some digging so I may not get to it until Saturday. :-(

**Comment by craigdrayton** [comment]
Thanks Larry! Let me know if I can give you any more information that'll help.

**Comment by craigdrayton** [comment]
Hi Larry, hope you're having a good weekend. Have you been able to take a look at this by any chance?
